name: Snowflake Deployment
run-name: ${{ github.actor }} started the snowflake ddl deployment for ${{ github.ref_name }} environment
on:
    push:
        branches: [dev]

jobs:
    validate-sql-hash:
        environment: dev
        runs-on: ubuntu-latest
        container:
            image: liquibase/liquibase:4.27
            options: --cpus 1
        steps:
            - name: check_env
              env:
                SF_URL: ${{ secrets.SF_URL }}
                SF_USER: ${{ secrets.SF_USER }}
                SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
              run: liquibase status --url=${SF_URL} --changelog-file="../changelog-master.xml" --driver='net.snowflake.client.jdbc.SnowflakeDriver' --username=${SF_USER} --password=${SF_PASSWORD} --logLevel=info

