name: Snowflake Deployment
run-name: ${{ github.actor }} started the Snowflake deployment
on:
    push:
        branches: [dev]

jobs:
    validate-sql:
        runs-on: ubuntu-latest
        container:
            image: liquibase/liquibase:4.27
            options: --cpus 1
        steps:
            - name: check_env
              run: (liquibase --version)

